{% set name = "s2geometry" %}
{% set version = "0.12.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/google/s2geometry/archive/v{{ version }}.tar.gz
  sha256: c09ec751c3043965a0d441e046a73c456c995e6063439a72290f661c1054d611
  patches:
    # missing DLL exports on windows (data)
    - dllexport.patch
    - python-setup.patch

build:
  number: 1
  run_exports:
    # breaking changes are expected in minor 0.x releases
    - {{ pin_subpackage('s2geometry', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler("cxx") }}
    - {{ stdlib("c") }}
    - cmake >=3.25,<4
    - make  # [unix]

  host:
    - openssl
    - libabseil
  run:
    - libabseil

outputs:

  - name: s2geometry

  - name: s2geometry-python
    script: install_python.sh  # [unix]
    script: install_python.bat  # [win]
    build:
    requirements:
      build:
        - {{ stdlib("c") }}
        - {{ compiler('cxx') }}
        - cmake
        - make  # [unix]
        - ninja  # [win]
        - python                                 # [build_platform != target_platform]
        - cross-python_{{ target_platform }}     # [build_platform != target_platform]
        - swig
      host:
        - python
        - pip
        - setuptools
        - libabseil
        - cmake-build-extension

      run:
        - libabseil
        - python
    test:
      source_files:
        - src/python/s2geometry_test.py
      commands:
        - python ./src/python/s2geometry_test.py
      imports:
        - s2geometry

test:
  files:
    run_test.bat
    run_test.sh

about:
  home: https://s2geometry.io/
  license: Apache-2.0
  license_file: LICENSE
  summary: Computational geometry and spatial indexing on the sphere.

  dev_url: https://github.com/google/s2geometry

extra:
  recipe-maintainers:
    - benbovy
    - hobu
