{% set name = "s2geometry" %}
{% set version = "0.13.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/google/s2geometry/archive/v{{ version }}.tar.gz
  sha256: 6091ca0138225f3effbd80b9c416b527c66eb30460f3f050f45345a3c0c1c79c
  patches:
    # missing DLL exports on windows (data)
    - dllexport.patch
    - python-setup.patch

build:
  number: 0
  run_exports:
    # breaking changes are expected in minor 0.x releases
    - {{ pin_subpackage('s2geometry', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler("cxx") }}
    - {{ stdlib("c") }}
    - cmake >=3.25,<4
    - make  # [unix]

  host:
    - openssl
    - libabseil
  run:
    - libabseil

test:
  files: run_test.bat run_test.sh

outputs:

  - name: s2geometry

  - name: s2geometry-python
    script: install_python.sh  # [unix]
    script: install_python.bat  # [win]
    requirements:
      build:
        - {{ stdlib("c") }}
        - {{ compiler('cxx') }}
        - cmake
        - make  # [unix]
        - ninja  # [win]
        - python                                 # [build_platform != target_platform]
        - cross-python_{{ target_platform }}     # [build_platform != target_platform]
        - cmake-build-extension                  # [build_platform != target_platform]
        - swig
      host:
        - python
        - pip
        - setuptools
        - libabseil
        - cmake-build-extension
        - openssl

      run:
        - libabseil
        - openssl
    test:
      source_files:
        - src/python/s2geometry_test.py
      commands:
        - python ./src/python/s2geometry_test.py > /dev/null
      imports:
        - s2geometry


about:
  home: https://s2geometry.io/
  license: Apache-2.0
  license_file: LICENSE
  summary: Computational geometry and spatial indexing on the sphere.

  dev_url: https://github.com/google/s2geometry

extra:
  recipe-maintainers:
    - benbovy
    - hobu
