{% set name = "s2geometry" %}
{% set version = "0.10.0-2022.02.23.00" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/google/s2geometry/archive/v{{ version }}.tar.gz
  sha256: ec707125c450a2e569555115aad6bacdb74a6be1320627f759b679141aab17db
  patches:
    # use gtest shipped by conda-forge instead of building it from source
    - use_installed_gtest.patch
    # fix osx-arm64 build (TODO: remove when absl is an external dependency)
    - fix_absl_unaligned_access.patch  # [build_platform != target_platform]

build:
  number: 0

requirements:
  build:
    - {{ compiler("cxx") }}
    - cmake >=3.12,<4
    - make  # [linux]
  host:
    - openssl
    - gtest
    - gmock

test:
  commands:
    - test -f ${PREFIX}/lib/libs2.dylib  # [osx]
    - test -f ${PREFIX}/lib/libs2.so     # [linux]
    - test -f ${PREFIX}/include/s2/s2cell.h  # [unix]
    - if not exist %LIBRARY_BIN%\s2.dll exit 1  # [win]
    - if not exist %LIBRARY_BIN%\libs2.dll exit 1  # [win]
    - if not exist %LIBRARY_LIB%\s2.lib exit 1  # [win]
    - if not exist %LIBRARY_LIB%\libs2.lib exit 1  # [win]
    - if not exist %LIBRARY_INC%\s2\s2cell.h exit 1  # [win]

about:
  home: https://s2geometry.io/
  license: Apache-2.0
  license_file: LICENSE
  summary: Computational geometry and spatial indexing on the sphere.

  dev_url: https://github.com/google/s2geometry

extra:
  recipe-maintainers:
    - benbovy
