{% set name = "s2geometry" %}
{% set version = "0.10.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/google/s2geometry/archive/v{{ version }}.tar.gz
  sha256: 1c17b04f1ea20ed09a67a83151ddd5d8529716f509dde49a8190618d70532a3d
  patches:
    # use gtest shipped by conda-forge instead of building it from source
    - use_installed_gtest.patch
    # TODO: remove for version > 0.10.0
    - allow_override_cpp_standard.patch
    # old gcc version used for linux builds?
    - fix_gcc_prid64.patch  # [linux]
    # missing DLL exports on windows (data)
    - dllexport.patch
    # disable failing test on Linux with last absl release
    # (disabled too in s2geometry head for other cases)
    - disable_linux_s2builder_test.patch

build:
  number: 2

requirements:
  build:
    - {{ compiler("cxx") }}
    - cmake >=3.12,<4
    - make  # [linux]
  host:
    - openssl
    - gtest
    - gmock
    - libabseil
  run:
    - libabseil

test:
  commands:
    - test -f ${PREFIX}/lib/libs2.dylib  # [osx]
    - test -f ${PREFIX}/lib/libs2.so     # [linux]
    - test -f ${PREFIX}/include/s2/s2cell.h  # [unix]
    - if not exist %LIBRARY_BIN%\s2.dll exit 1  # [win]
    - if not exist %LIBRARY_BIN%\libs2.dll exit 1  # [win]
    - if not exist %LIBRARY_LIB%\s2.lib exit 1  # [win]
    - if not exist %LIBRARY_LIB%\libs2.lib exit 1  # [win]
    - if not exist %LIBRARY_INC%\s2\s2cell.h exit 1  # [win]

about:
  home: https://s2geometry.io/
  license: Apache-2.0
  license_file: LICENSE
  summary: Computational geometry and spatial indexing on the sphere.

  dev_url: https://github.com/google/s2geometry

extra:
  recipe-maintainers:
    - benbovy
